services:
  drone-srcb:
    build: .
    environment:
      API_ID: $API_ID  
      API_HASH: $API_HASH  
      BOT_TOKEN: $BOT_TOKEN 
      OWNER-ID: $OWNER-ID
      LOG_CHANNEL: $LOG_CHANNEL
    ports:
      - 8080
    resources:
      cpu: 1000m
      memory: 3Gi
